name: maws
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10
  - numba=0.57.1
  - openmm=8.0.0
  - ambertools=23.3
  - mpmath>=1.2.1
  - ipykernel
  - jupyterlab
  - pip

dev-dependencies:
  - pre-commit
  - ruff
  - black
